CREATE DATABASE IF NOT EXISTS Sistema_Cadastro;
USE Sistema_Cadastro;

CREATE TABLE cliente (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DATA_NASCIMENTO VARCHAR(20) NOT NULL,
SENHA VARCHAR(15) NOT NULL,
ATIVO TINYINT(1) NOT NULL DEFAULT 1,
PRIMARY KEY (ID),
UNIQUE KEY uk_cliente_cpf (CPF),
KEY ix_cliente_nome (NOME)

);

CREATE TABLE usuario(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
SENHA_HALT CHAR(64) NOT NULL,
SENHA_SALT CHAR (32) NOT NULL,
PERFIL ENUM('ADMIN', 'ATENDENTE') NOT NULL,
ATIVO TINYINT(1) NOT NULL DEFAULT 1,
PRIMARY KEY (ID),
UNIQUE KEY uk_usuario_login (LOGIN)
);

